name: Update code_tree_readme

on:
  schedule:
    - cron: "0 9 * * *"  # 매일 오전 9시 (UTC 기준)
  workflow_dispatch:  # 수동 실행

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Node.js 20과 호환

    - name: Set up Python
      uses: actions/setup-python@v4  # Node.js 20과 호환
      with:
        python-version: "3.9"

    - name: Run Python Script
      run: python code_tree_readme.py
